[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "/_index"
weight = 1

[[main]]
name = "Accelerator R&D"
parent = "About"
pageRef = "posts/accelerator"
weight = 2

[[main]]
name = "Detector R&D"
parent = "About"
pageRef = "posts/detector"
weight = 3

[[main]]
name = "Physics Case"
parent = "About"
pageRef = "posts/physics"
weight = 4

[[main]]
name = "Dedicated Software"
parent = "About"
pageRef = "posts/reconstruction"
weight = 5


[[main]]
name = "National Lab Accelerator Study Group"
parent = "About"
pageRef = "otherorgs/nationallabstudygroup"
weight = 6

[[main]]
name = "IMCC"
parent = "About"
pageRef = "otherorgs/imcc"
weight = 7

[[main]]
name = "Press"
pageRef = "press"
weight = 10

[[main]]
name = "Events"
pageRef = "events"
weight = 20

[[main]]
name = "Resources"
pageRef = "resources"
weight = 30

[[main]]
name = "Contact"
pageRef = "contact"
weight = 40

[[main]]
name = "People"
pageRef = "people"
weight = 50

[[main]]
name = "Merch"
pageRef = "merch"
weight = 60



[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/muoncollider.us/"
  weight = 9992


[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/company/muoncollider-us/"
  weight = 9992



#[[footer]]
#none = "none"

[[footer]]
name = "Email us"
url = "mailto:usmcc-coord@fnal.gov"


